version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cdylib
  - chrono
  - clippy
  - datafusion
  - deltalake
  - healthcheck
  - hudi
  - ipynb
  - jdbc
  - jovyan
  - jsonschema
  - justfile
  - kubeconfig
  - lakehouse
  - lakehouses
  - Leptos
  - minioadmin
  - monokai
  - nocapture
  - orasi
  - OTAP
  - prost
  - reqwest
  - rlib
  - rustc
  - rustup
  - serde
  - sqlx
  - stylesheet
  - thiserror
  - trino
ignoreWords: []
import: []
