version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cdylib
  - chrono
  - clippy
  - dashmap
  - datafusion
  - datatypes
  - deltalake
  - fastrand
  - grpcio
  - healthcheck
  - hudi
  - ipynb
  - jdbc
  - jovyan
  - jsonschema
  - jsonwebtoken
  - justfile
  - kubeconfig
  - lakehouse
  - lakehouses
  - Leptos
  - minioadmin
  - monokai
  - nanos
  - nocapture
  - orasi
  - OTAP
  - prost
  - protoc
  - protos
  - pushdown
  - rdkafka
  - reqwest
  - rlib
  - rustc
  - rustup
  - sasl
  - serde
  - sqlx
  - stylesheet
  - sysinfo
  - thiserror
  - trino
  - utoipa
ignoreWords: []
import: []
