kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Cluster name
name: orasi-test

# Nodes configuration
nodes:
  # Control plane node
  - role: control-plane
    image: kindest/node:v1.28.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      # HTTPS
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      # Bridge API
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # Schema Registry
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
      # Web UI
      - containerPort: 30082
        hostPort: 30082
        protocol: TCP
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock

  # Worker nodes
  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock

  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock

# Feature gates for testing
featureGates:
  # Enable features that might be useful for testing
  EphemeralContainers: true
  LocalStorageCapacityIsolation: true

# Runtime configuration
runtimeConfig:
  # Enable admission controllers
  admissionregistration.k8s.io/v1: "true"
  apiextensions.k8s.io/v1: "true"
  apiregistration.k8s.io/v1: "true"
  apps/v1: "true"
  autoscaling/v1: "true"
  autoscaling/v2: "true"
  batch/v1: "true"
  certificates.k8s.io/v1: "true"
  coordination.k8s.io/v1: "true"
  discovery.k8s.io/v1: "true"
  events.k8s.io/v1: "true"
  flowcontrol.apiserver.k8s.io/v1beta1: "true"
  flowcontrol.apiserver.k8s.io/v1beta2: "true"
  networking.k8s.io/v1: "true"
  node.k8s.io/v1: "true"
  policy/v1: "true"
  rbac.authorization.k8s.io/v1: "true"
  scheduling.k8s.io/v1: "true"
  storage.k8s.io/v1: "true"

# Networking configuration
networking:
  # Use Calico for better network policies
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # Enable IPv6 (optional)
  ipFamily: ipv4
