# Orasi Gateway Configuration

# Gateway identification
gateway_id = "orasi-gateway-1"

# Gateway endpoints
gateway_endpoint = "0.0.0.0:8080"
health_endpoint = "0.0.0.0:8081"
metrics_endpoint = "0.0.0.0:9090"
admin_endpoint = "0.0.0.0:8082"

# Service discovery configuration
[service_discovery]
backend = "Etcd"
endpoints = ["http://localhost:2379"]
refresh_interval = 30
health_check_interval = 10

# Load balancing configuration
[load_balancing]
algorithm = "RoundRobin"
health_check_enabled = true
health_check_interval = 30
health_check_timeout = 5
sticky_sessions_enabled = false
sticky_session_timeout = 300

# Routing configuration
[routing]
timeout_seconds = 30
max_retries = 3
retry_delay_ms = 1000
circuit_breaker_enabled = true
circuit_breaker_threshold = 5
circuit_breaker_timeout = 60

# Default routes
[[routing.routes]]
path = "/api/v1/*"
method = "*"
service_name = "bridge-api"
priority = 100
rules = []

[[routing.routes]]
path = "/agent/*"
method = "*"
service_name = "orasi-agent"
priority = 90
rules = []

[[routing.routes]]
path = "/health"
method = "GET"
service_name = "gateway-health"
priority = 200
rules = []

[[routing.routes]]
path = "/metrics"
method = "GET"
service_name = "gateway-metrics"
priority = 200
rules = []

# Security configuration
[security]
authentication_enabled = false
authorization_enabled = false
cors_enabled = true
cors_origins = ["*"]
cors_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_headers = ["*"]
request_validation_enabled = true
max_request_size = 10485760  # 10MB

# Rate limiting configuration
[rate_limiting]
global_rps = 1000
per_client_rps = 100
per_endpoint_rps = 500
burst_size = 200
window_size_seconds = 60
enabled = true

# TLS configuration
[tls]
enabled = false
cert_file = "/etc/ssl/certs/gateway.crt"
key_file = "/etc/ssl/private/gateway.key"
ca_file = "/etc/ssl/certs/ca.crt"
verify_client = false
min_tls_version = "1.2"
cipher_suites = ["TLS_AES_128_GCM_SHA256", "TLS_AES_256_GCM_SHA384"]

# Logging configuration
[logging]
level = "info"
format = "json"
output = "stdout"
file_path = ""
max_file_size = 104857600  # 100MB
max_files = 10
enable_structured_logging = true

# Metrics configuration
[metrics]
enabled = true
prometheus_enabled = true
custom_metrics_enabled = true
histogram_buckets = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
collection_interval = 15

# Performance configuration
[performance]
worker_threads = 4
max_connections = 10000
connection_timeout = 30
idle_timeout = 300
keep_alive_timeout = 60
max_concurrent_requests = 1000
request_buffer_size = 8192
response_buffer_size = 8192

# Caching configuration
[caching]
enabled = false
cache_size = 1000
ttl_seconds = 300
eviction_policy = "lru"
distributed_cache_enabled = false
distributed_cache_endpoints = []

# Monitoring configuration
[monitoring]
health_check_enabled = true
health_check_interval = 30
metrics_collection_enabled = true
metrics_collection_interval = 15
tracing_enabled = true
tracing_sampling_rate = 0.1
alerting_enabled = false
alerting_endpoints = []

# Network configuration
[network]
bind_address = "0.0.0.0"
port = 8080
ssl_port = 8443
proxy_protocol_enabled = false
real_ip_header = "X-Real-IP"
forwarded_for_header = "X-Forwarded-For"
trusted_proxies = ["127.0.0.1", "::1"]
max_headers = 100
max_header_size = 8192
