# Zola configuration for Orasi documentation
base_url = "https://orasi.dev"
title = "Orasi Documentation"
description = "Comprehensive documentation for the Orasi data platform"
default_language = "en"

# Theme configuration
theme = "adidoks"

# Build settings
build_search_index = true
generate_feeds = true

# Link checker settings
link_checker.skip_anchor_prefixes = ["#"]
link_checker.external_validation = false

# Markdown settings
markdown.highlight_code = true
markdown.highlight_theme = "monokai"
markdown.external_links_target_blank = true
markdown.external_links_no_follow = true

# Taxonomies
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", feed = true},
]

# Additional settings for adidoks theme
[extra]
# Please don't change the following line
version = "2.0.0"

# Your information
title = "Orasi Documentation"
description = "Comprehensive documentation for the Orasi data platform"
author = "Orasi Team"
# Your repository
repo_url = "https://github.com/your-org/orasi"
# Your name
repo_name = "orasi"

# Header configuration
[extra.header]
# Title shown in the header
title = "Orasi"
# Logo shown in the header
logo = "orasi-logo.svg"
# Show a search bar in the header
show_search = true
# Show the theme switcher in the header
show_theme_toggle = true
# Show the repository button in the header
show_repository_button = true

# Navigation configuration
[extra.nav]
# Navigation links
[[extra.nav.links]]
text = "Home"
url = "/"
home = true

[[extra.nav.links]]
text = "Getting Started"
url = "/getting-started/"

[[extra.nav.links]]
text = "Components"
url = "/components/"

[[extra.nav.links]]
text = "API Reference"
url = "/api/"

[[extra.nav.links]]
text = "Examples"
url = "/examples/"

# Footer configuration
[extra.footer]
# Footer links
[[extra.footer.links]]
text = "GitHub"
url = "https://github.com/your-org/orasi"

[[extra.footer.links]]
text = "Discord"
url = "https://discord.gg/orasi"

# Social media links
[extra.social]
github = "https://github.com/your-org/orasi"
twitter = "https://twitter.com/orasi_dev"
